external_components:
  - source:
      type: git
      url: https://github.com/vbaksa/esphome
      ref: dev
    components: [lilygo_t5_47_display, lilygo_t5_47_battery]


substitutions:
  esp_name: ESP Display #Device Name
  esp_hostname: esp-display
  run_time: 30s #can be as long as needed to get data
  sleep_time: 270s # normal sleep time
  night_sleep_time: 6h # 1st sleep time after midnight

esphome:
  name: ${esp_hostname}
  platform: ESP32
  board: esp32dev

wifi:
  ssid: ***REMOVED***
  password: ***REMOVED***
  manual_ip:
    static_ip: 192.168.1.49
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true
  power_save_mode: HIGH

ota:
  password: ***REMOVED***
  id: ota_id


# logger:
#   level: debug

api:
  password: ***REMOVED***


deep_sleep:
  id: deep_sleep_control
  sleep_duration: ${sleep_time}
  touch_wakeup: true





time:
  - platform: sntp
  - platform: homeassistant
    id: ntp
  - platform: homeassistant
    on_time:
      # Every 15 minutes
      - seconds: 0
        minutes: 0
        hours: /4
        then:
          - component.update: battery
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 0
        then:
          - display.page.show: backgroundPage
          - component.update: eInkDisplay
  - platform: homeassistant
    on_time:
      - seconds: 10,40
        then:
          - component.update: eInkDisplay
  - platform: homeassistant
    on_time:
      # Every 30 seconds
      - seconds: 0,30
        then:
          - if:
              condition:
                binary_sensor.is_on: prevent_deep_sleep
              then:
                - logger.log: 'Skipping sleep, per prevent_deep_sleep'
                - deep_sleep.prevent: deep_sleep_control
              else:
                - deep_sleep.enter: deep_sleep_control

sun:
  latitude: 40.7818°
  longitude: -73.9175°


# Touch

esp32_touch:

binary_sensor:
  - platform: esp32_touch
    name: "TouchTest"
    pin: GPIO13
    threshold: 700
    wakeup_threshold: 700
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: "${esp_name} Button 1"
    internal: true
    on_press:
      then:
       - script.execute: refresh_display
  - platform: homeassistant
    id: prevent_deep_sleep
    name: Prevent Deep Sleep
    entity_id: input_boolean.prevent_deep_sleep

sensor:
  - platform: lilygo_t5_47_battery
    id: battery
    update_interval: never
    voltage:
      name: "Battery Voltage"
#Bikes
  - platform: homeassistant
    id: crescent
    entity_id: sensor.crescentbikes
    internal: true
  - platform: homeassistant
    id: shore
    entity_id: sensor.shorebikes
    internal: true
  - platform: homeassistant
    id: parkside
    entity_id: sensor.parksidebikes
    internal: true
  - platform: homeassistant
    id: cherry
    entity_id: sensor.cherrybikes
    internal: true
#Sun
  - platform: sun
    name: Sun Elevation
    type: elevation
    id: sunElevation
    internal: true


text_sensor:
#Busses
  #Q69
    #Steinway
  - platform: homeassistant
    id: q69sA
    entity_id: sensor.q69s0
    internal: true
    on_value:
      then:
        - display.page.show: busRefresh
    filters:
    - substitute:
      - "unavailable -> "
  - platform: homeassistant
    id: q69sB
    entity_id: sensor.q69s1
    internal: true
    filters:
    - substitute:
      - "unavailable -> "
  - platform: homeassistant
    id: q69sC
    entity_id: sensor.q69s2
    internal: true
    filters:
    - substitute:
      - "unavailable -> "
    #Plaza
  - platform: homeassistant
    id: q69pA
    entity_id: sensor.q69p0
    internal: true
    on_value:
      then:
        - display.page.show: busRefresh
    filters:
    - substitute:
      - "unavailable -> "
  - platform: homeassistant
    id: q69pB
    entity_id: sensor.q69p1
    internal: true
    filters:
    - substitute:
      - "unavailable -> "
  - platform: homeassistant
    id: q69pC
    entity_id: sensor.q69p2
    internal: true
    filters:
    - substitute:
      - "unavailable -> "
  #Q100
    #Steinway
  - platform: homeassistant
    id: q100sA
    entity_id: sensor.q100s0
    internal: true
    on_value:
      then:
        - display.page.show: busRefresh
    filters:
    - substitute:
      - "unavailable -> "
  - platform: homeassistant
    id: q100sB
    entity_id: sensor.q100s1
    internal: true
    filters:
    - substitute:
      - "unavailable -> "
  - platform: homeassistant
    id: q100sC
    entity_id: sensor.q100s2
    internal: true
    filters:
    - substitute:
      - "unavailable -> "
    #Plaza
  - platform: homeassistant
    id: q100pA
    entity_id: sensor.q100p0
    internal: true
    on_value:
      then:
        - display.page.show: busRefresh
    filters:
    - substitute:
      - "unavailable -> "
  - platform: homeassistant
    id: q100pB
    entity_id: sensor.q100p1
    internal: true
    filters:
    - substitute:
      - "unavailable -> "
  - platform: homeassistant
    id: q100pC
    entity_id: sensor.q100p2
    internal: true
    filters:
    - substitute:
      - "unavailable -> "


script:
  - id: refresh_display
    then:
      - display.page.show: black
      - component.update: eInkDisplay
      - display.page.show: blank
      - component.update: eInkDisplay


font:
  - file: "/Users/donromaniello/Library/Fonts/Ubuntu-Regular.ttf"
    id: ubuntu36
    size: 36
  - file: "/Users/donromaniello/Library/Fonts/Ubuntu-Light.ttf"
    id: ubuntu40
    size: 40
  - file: "/Users/donromaniello/Library/Fonts/Ubuntu-Light.ttf"
    id: ubuntu55
    size: 55
  - file: "/Users/donromaniello/Library/Fonts/Ubuntu-Light.ttf"
    id: ubuntu88
    size: 88

image:
  - file: "./images/lilyLayoutScaledBackground.png"
    id: background
    dither: FLOYDSTEINBERG

# Display is not centered.
# Shift everything right by 4 px, giving 536 width
display:
  - platform: lilygo_t5_47_display
    id: eInkDisplay
    clear: false
    update_interval: never
    rotation: 270
    pages:
      - id: busRefresh
        lambda: |-
          // Steinway
          it.print(64, 17, id(ubuntu36), "Steinway");
          it.line(42, 61, 240, 61);
          it.line(63, 107, 92, 107);
          it.print(102, 72, id(ubuntu40), "q69");
          it.line(189, 107, 218, 107);
          it.line(63, 265, 78, 265);
          it.print(90, 232, id(ubuntu40), "q100");
          it.line(200, 265, 215, 265);

          // Plaza
          it.print(359, 17, id(ubuntu36), "Plaza");
          it.line(304, 61, 502, 61);
          it.line(321, 107, 351, 107);
          it.print(368, 72, id(ubuntu40), "q69");
          it.line(452, 107, 482, 107);
          it.line(321, 265, 351, 265);
          it.print(357, 232, id(ubuntu40), "q100");
          it.line(452, 265, 482, 265);

          it.printf(26, 124, id(ubuntu88), "%s", id(q69sA).state.c_str());
          it.printf(291, 124, id(ubuntu88), "%s", id(q69pA).state.c_str());
          it.printf(26, 283, id(ubuntu88), "%s", id(q100sA).state.c_str());
          it.printf(291, 283, id(ubuntu88), "%s", id(q100pA).state.c_str());
      - id: busBlank
        lambda: |-
          it.filled_rectangle(36, 137, 210, 65, COLOR_OFF);
          it.filled_rectangle(281, 137, 210, 65, COLOR_OFF);
          it.filled_rectangle(36, 296, 210, 65, COLOR_OFF);
          it.filled_rectangle(281, 296, 210, 65, COLOR_OFF);
          // Steinway
          it.print(64, 17, id(ubuntu36), "Steinway");
          it.print(102, 72, id(ubuntu40), "q69");
          it.print(90, 232, id(ubuntu40), "q100");

          // Plaza
          it.print(359, 17, id(ubuntu36), "Plaza");
          it.print(368, 72, id(ubuntu40), "q69");
          it.print(357, 232, id(ubuntu40), "q100");

          it.printf(26, 124, id(ubuntu88), "%s", id(q69sA).state.c_str());
          it.printf(291, 124, id(ubuntu88), "%s", id(q69pA).state.c_str());
          it.printf(26, 283, id(ubuntu88), "%s", id(q100sA).state.c_str());
          it.printf(291, 283, id(ubuntu88), "%s", id(q100pA).state.c_str());

      - id: backgroundPage
        lambda: |-
          it.image(12, 8, id(background));

          // Steinway
          it.print(64, 17, id(ubuntu36), "Steinway");
          it.line(42, 61, 240, 61);
          it.line(63, 107, 92, 107);
          it.print(102, 72, id(ubuntu40), "q69");
          it.line(189, 107, 218, 107);
          it.line(63, 265, 78, 265);
          it.print(90, 232, id(ubuntu40), "q100");
          it.line(200, 265, 215, 265);

          // Plaza
          it.print(359, 17, id(ubuntu36), "Plaza");
          it.line(304, 61, 502, 61);
          it.line(321, 107, 351, 107);
          it.print(368, 72, id(ubuntu40), "q69");
          it.line(452, 107, 482, 107);
          it.line(321, 265, 351, 265);
          it.print(357, 232, id(ubuntu40), "q100");
          it.line(452, 265, 482, 265);

      - id: black
        lambda: |-
          it.filled_rectangle(0,0, 540, 960);

      - id: blank
        lambda: |-
          it.filled_rectangle(0,0, 540, 960, COLOR_OFF);

